CC = gcc
CFLAGS = -Wall
LIBS = -math4610
LDFLAGS = ~/Desktop/USU\ Year\ 2/CS\ 2610/assignment4

central_difference: central-difference.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	rm -f central_difference